// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{0}
}

type Fields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []byte                 `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fields) Reset() {
	*x = Fields{}
	mi := &file_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fields) ProtoMessage() {}

func (x *Fields) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fields.ProtoReflect.Descriptor instead.
func (*Fields) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{1}
}

func (x *Fields) GetFields() []byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddServer     uint32                 `protobuf:"varint,1,opt,name=add_server,json=addServer,proto3" json:"add_server,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{3}
}

func (x *HandleRequest) GetAddServer() uint32 {
	if x != nil {
		return x.AddServer
	}
	return 0
}

func (x *HandleRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Fingerprints  []*Fingerprint         `protobuf:"bytes,3,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{4}
}

func (x *Host) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Host) GetFingerprints() []*Fingerprint {
	if x != nil {
		return x.Fingerprints
	}
	return nil
}

type Fingerprint struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostID uint32                 `protobuf:"varint,2,opt,name=hostID,proto3" json:"hostID,omitempty"`
	// json data
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Service       string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Protocol      string `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fingerprint) Reset() {
	*x = Fingerprint{}
	mi := &file_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprint) ProtoMessage() {}

func (x *Fingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fingerprint.ProtoReflect.Descriptor instead.
func (*Fingerprint) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{5}
}

func (x *Fingerprint) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fingerprint) GetHostID() uint32 {
	if x != nil {
		return x.HostID
	}
	return 0
}

func (x *Fingerprint) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Fingerprint) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Fingerprint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Fingerprint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostID        uint32                 `protobuf:"varint,2,opt,name=hostID,proto3" json:"hostID,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{6}
}

func (x *Label) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetHostID() uint32 {
	if x != nil {
		return x.HostID
	}
	return 0
}

func (x *Label) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Scan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Targets       []string               `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Flags         string                 `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{7}
}

func (x *Scan) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Scan) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Scan) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *Scan) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scanner       string                 `protobuf:"bytes,5,opt,name=scanner,proto3" json:"scanner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{8}
}

func (x *Source) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Source) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Source) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{9}
}

func (x *IDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{11}
}

func (x *QueryResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

var File_module_proto protoreflect.FileDescriptor

const file_module_proto_rawDesc = "" +
	"\n" +
	"\fmodule.proto\x12\x05proto\"\a\n" +
	"\x05Empty\" \n" +
	"\x06Fields\x12\x16\n" +
	"\x06fields\x18\x01 \x01(\fR\x06fields\"+\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"R\n" +
	"\rHandleRequest\x12\x1d\n" +
	"\n" +
	"add_server\x18\x01 \x01(\rR\taddServer\x12\"\n" +
	"\x05event\x18\x02 \x01(\v2\f.proto.EventR\x05event\"h\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x126\n" +
	"\ffingerprints\x18\x03 \x03(\v2\x12.proto.FingerprintR\ffingerprints\"\x93\x01\n" +
	"\vFingerprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06hostID\x18\x02 \x01(\rR\x06hostID\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\"E\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06hostID\x18\x02 \x01(\rR\x06hostID\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"^\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\tR\x05flags\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\"^\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\ascanner\x18\x05 \x01(\tR\ascanner\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"2\n" +
	"\rQueryResponse\x12!\n" +
	"\x05hosts\x18\x01 \x03(\v2\v.proto.HostR\x05hosts2\x8a\x01\n" +
	"\x06Module\x12'\n" +
	"\tPropagate\x12\f.proto.Empty\x1a\f.proto.Empty\x12)\n" +
	"\n" +
	"Properties\x12\f.proto.Empty\x1a\r.proto.Fields\x12,\n" +
	"\x06Handle\x12\x14.proto.HandleRequest\x1a\f.proto.Empty2\xeb\x02\n" +
	"\aAdapter\x12(\n" +
	"\aGetHost\x12\x10.proto.IDRequest\x1a\v.proto.Host\x12,\n" +
	"\tGetSource\x12\x10.proto.IDRequest\x1a\r.proto.Source\x12(\n" +
	"\aGetScan\x12\x10.proto.IDRequest\x1a\v.proto.Scan\x12&\n" +
	"\bAddLabel\x12\f.proto.Label\x1a\f.proto.Empty\x122\n" +
	"\x0eAddFingerprint\x12\x12.proto.Fingerprint\x1a\f.proto.Empty\x12$\n" +
	"\aAddScan\x12\v.proto.Scan\x1a\f.proto.Empty\x12(\n" +
	"\tAddSource\x12\r.proto.Source\x1a\f.proto.Empty\x122\n" +
	"\x05Query\x12\x13.proto.QueryRequest\x1a\x14.proto.QueryResponseB\tZ\a./protob\x06proto3"

var (
	file_module_proto_rawDescOnce sync.Once
	file_module_proto_rawDescData []byte
)

func file_module_proto_rawDescGZIP() []byte {
	file_module_proto_rawDescOnce.Do(func() {
		file_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)))
	})
	return file_module_proto_rawDescData
}

var file_module_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_module_proto_goTypes = []any{
	(*Empty)(nil),         // 0: proto.Empty
	(*Fields)(nil),        // 1: proto.Fields
	(*Event)(nil),         // 2: proto.Event
	(*HandleRequest)(nil), // 3: proto.HandleRequest
	(*Host)(nil),          // 4: proto.Host
	(*Fingerprint)(nil),   // 5: proto.Fingerprint
	(*Label)(nil),         // 6: proto.Label
	(*Scan)(nil),          // 7: proto.Scan
	(*Source)(nil),        // 8: proto.Source
	(*IDRequest)(nil),     // 9: proto.IDRequest
	(*QueryRequest)(nil),  // 10: proto.QueryRequest
	(*QueryResponse)(nil), // 11: proto.QueryResponse
}
var file_module_proto_depIdxs = []int32{
	2,  // 0: proto.HandleRequest.event:type_name -> proto.Event
	5,  // 1: proto.Host.fingerprints:type_name -> proto.Fingerprint
	4,  // 2: proto.QueryResponse.hosts:type_name -> proto.Host
	0,  // 3: proto.Module.Propagate:input_type -> proto.Empty
	0,  // 4: proto.Module.Properties:input_type -> proto.Empty
	3,  // 5: proto.Module.Handle:input_type -> proto.HandleRequest
	9,  // 6: proto.Adapter.GetHost:input_type -> proto.IDRequest
	9,  // 7: proto.Adapter.GetSource:input_type -> proto.IDRequest
	9,  // 8: proto.Adapter.GetScan:input_type -> proto.IDRequest
	6,  // 9: proto.Adapter.AddLabel:input_type -> proto.Label
	5,  // 10: proto.Adapter.AddFingerprint:input_type -> proto.Fingerprint
	7,  // 11: proto.Adapter.AddScan:input_type -> proto.Scan
	8,  // 12: proto.Adapter.AddSource:input_type -> proto.Source
	10, // 13: proto.Adapter.Query:input_type -> proto.QueryRequest
	0,  // 14: proto.Module.Propagate:output_type -> proto.Empty
	1,  // 15: proto.Module.Properties:output_type -> proto.Fields
	0,  // 16: proto.Module.Handle:output_type -> proto.Empty
	4,  // 17: proto.Adapter.GetHost:output_type -> proto.Host
	8,  // 18: proto.Adapter.GetSource:output_type -> proto.Source
	7,  // 19: proto.Adapter.GetScan:output_type -> proto.Scan
	0,  // 20: proto.Adapter.AddLabel:output_type -> proto.Empty
	0,  // 21: proto.Adapter.AddFingerprint:output_type -> proto.Empty
	0,  // 22: proto.Adapter.AddScan:output_type -> proto.Empty
	0,  // 23: proto.Adapter.AddSource:output_type -> proto.Empty
	11, // 24: proto.Adapter.Query:output_type -> proto.QueryResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_module_proto_init() }
func file_module_proto_init() {
	if File_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_module_proto_goTypes,
		DependencyIndexes: file_module_proto_depIdxs,
		MessageInfos:      file_module_proto_msgTypes,
	}.Build()
	File_module_proto = out.File
	file_module_proto_goTypes = nil
	file_module_proto_depIdxs = nil
}
